resources:
  - name: git_repo 
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: GitHub
      # Repository path, including org name/repo name
      path: MaharshiPatel/SwampUp2021
      branches:
        # Specifies which branches will trigger dependent steps
        include: main

  - name: build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory

pipelines:
  - name: npm_example_pipeline
    configuration:
      environmentVariables:
        readOnly:
           my_env_var: '1.0.$run_number'
    steps:
      - name: npm_build_step
        type: NpmBuild
        configuration:
          repositoryName: su201-npm      # required, npm repository name on artifacctory
          sourceLocation: ./SU-201-Intro-to-JFrog-Xray/npm-example/      # required, location of package.json file
          integrations:
            - name:  Artifactory  # required 
          inputResources:
            - name: git_repo   # required

      - name: npm_publish_step
        type: NpmPublish
        configuration:
          # for payloadType npm:
          repositoryName: su201-npm        # required, npm repository name on artifactory
          autoPublishBuildInfo: true       # optional
          integrations:
            - name: Artifactory      # required
          inputSteps:
            - name: build_info      # required
          outputResources:
            - name: build_info   
        
      - name: npm_build_scan
        type: XrayScan
        configuration:
          failOnScan: false                      # default true
          inputResources:
            - name: build_info           # required
              trigger: true
          outputResources:
            - name: build_info          # optional
  
  - name: mvn_example_pipeline
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          deployerSnapshotRepo: su201-libs-snapshot
          deployerReleaseRepo:  su201-libs-release
          sourceLocation: ./SU-201-Intro-to-JFrog-Xray/maven-example/
          inputResources:
            - name: git_repo
          integrations:
            - name: Artifactory
      
      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: build_info
          outputResources:
            - name: build_info

      - name: mvn_build_scan
        type: XrayScan
        configuration:
          failOnScan: false                      # default true
          inputResources:
            - name: build_info           # required
              trigger: true
          outputResources:
            - name: build_info          # optional